### PR TITLE
Add Apache license header for skywalking.config.pb.html

### PR DESCRIPTION
**Pull request by SataQiu**
Add Apache license header for skywalking.config.pb.html.
Ref: apache/skywalking#2531
/cc @wu-sheng

### CODE REVIEW

**Comment by SataQiu** [comment]
@wu-sheng Thanks.
The code has been updated.
But I don't know how to deal with the following code:
```
---
title: Apache SkyWalking
description: Adapter to deliver metrics to Apache SkyWalking.
location: https://istio.io/docs/reference/config/policy-and-telemetry/adapters/apache-skywalking.html
layout: protoc-gen-docs
generator: protoc-gen-docs
provider: Apache SkyWalking
contact_email: dev@skywalking.apache.org
support_link:
source_link: https://github.com/apache/incubator-skywalking
latest_release_link: https://skywalking.apache.org/downloads/
helm_chart_link:
istio_versions: "1.0.3, 1.0.4, 1.1.0, 1.1.1"
supported_templates: metric
logo_link: https://github.com/apache/incubator-skywalking-website/raw/master/docs/.vuepress/public/assets/logo.svg
number_of_entries: 1
---
```
The attribute information is not HTML.

**Comment by wu-sheng** [comment]
What's about the code? This is a templatebased on istio.io required.

**Comment by SataQiu** [comment]
So how do we add the apache header to this file? WDYT?

**Comment by SataQiu** [comment]
Can this PR be merged now? Is there anything else that needs to be done? @wu-sheng 
I think I need more of your advice!

**Comment by wu-sheng** [comment]
Done.

**Comment by SataQiu** [comment]
Thank you so much! :+1:

**Pull request merged**
